ckpt_path: /mnt/data1tb/vinh/ISSM-SAR/checkpoints/lightning_20260307-174929-VH/best-ssim-epoch=07-step=136268-val_ssim=Metrics/Val/SSIM=0.3804.ckpt
device: cuda
limit: null # Optional: Limit number of images to infer (e.g., 100). Set null for all.

normalize:
  mean: 0.5
  std: 0.5

input:
  s1t1_path: /mnt/data1tb/vinh/ISSM-SAR/dataset/vh_dataset_splited/valid/S1T1
  s1t2_path: /mnt/data1tb/vinh/ISSM-SAR/dataset/vh_dataset_splited/valid/S1T2
  npy_in_0_1: true # If true, input .npy files are assumed to be in [0,1] and will be converted to model input via (x-mean)/std

output:
  s1sr_path: 
  save_path: /mnt/data1tb/vinh/ISSM-SAR/infer-results/valid-set/lightning_20260307-174929-VH/best-ssim-epoch=07-step=136268-val_ssim=Metrics/
  save_raw: true # Save raw output as .npy [-1, 1]
  export_npy_0_1: true # If true, also export the denormalized final output as .npy with values in [0,1]

# Model architecture config
model:
  num_ifs: 3
  use_bn: False
  use_gn: True

  pfe:
    in_channels: 1
    out_channels: 80
  
  hfe:
    in_c: 80
    out_c: 80
    kernel_size: 6
    padding: 2
    stride: 2
    num_blocks: 4
  
  rec:
    in_c: 80
    out_c: 1

  ifs:
    in_c: 80
    out_c: 80
    num_groups: 3
    kernel_size: 6
    padding: 2
    stride: 2